version: 1
services:
  - type: web
    name: RealHome
    env: static
    buildCommand: npm install
    publishDirectory: build
    rewrites:
      - source: /<*>  # Matches all routes
        destination: /index.html  # Serve index.html for all routes
